export const books = [
  {
    id: "1",
    slug: "caminho-a-cristo",
    title: "Caminho a Cristo",
    author: "Ellen G. White",
    description: "Guia espiritual sobre fé, arrependimento e relacionamento com Jesus.",
    category: "Vida Cristã",
    year: "1892",
    series: "Espiritual",
    cover: "/images/books/caminho-a-cristo.webp",
    downloadUrl: "/books/caminho-a-cristo.pdf",
    featured: true,
  },
  {
    id: "2",
    slug: "patriarcas-e-profetas",
    title: "Patriarcas e Profetas",
    author: "Ellen G. White",
    description: "História bíblica desde a criação até ao reinado de Davi.",
    category: "História Bíblica",
    year: "1890",
    series: "Conflito dos Séculos",
    cover: "/images/books/patriarcas-e-profetas.webp",
    downloadUrl: "/books/patriarcas-e-profetas.pdf",
  },
  {
    id: "3",
    slug: "profetas-e-reis",
    title: "Profetas e Reis",
    author: "Ellen G. White",
    description: "História dos reis de Israel e Judá.",
    category: "História Bíblica",
    year: "1917",
    series: "Conflito dos Séculos",
    cover: "/images/books/profetas-e-reis.webp",
    downloadUrl: "/books/profetas-e-reis.pdf",
  },
  {
    id: "4",
    slug: "o-grande-conflito",
    title: "O Grande Conflito",
    author: "Ellen G. White",
    description: "A batalha entre o bem e o mal ao longo da história.",
    category: "Profecia",
    year: "1911",
    series: "Conflito dos Séculos",
    cover: "/images/books/o-grande-conflito.webp",
    downloadUrl: "/books/o-grande-conflito.pdf",
  },
  {
    id: "5",
    slug: "o-desejado-de-todas-as-nacoes",
    title: "O Desejado de Todas as Nações",
    author: "Ellen G. White",
    description: "A vida e ministério de Jesus Cristo.",
    category: "Vida de Cristo",
    year: "1898",
    series: "Conflito dos Séculos",
    cover: "/images/books/o-desejado-de-todas-as-nacoes.webp",
    downloadUrl: "/books/o-desejado-de-todas-as-nacoes.pdf",
  },
  {
    id: "6",
    slug: "atos-dos-apostolos",
    title: "Atos dos Apóstolos",
    author: "Ellen G. White",
    description: "A história da igreja primitiva.",
    category: "Igreja",
    year: "1911",
    series: "Conflito dos Séculos",
    cover: "/images/books/atos-dos-apostolos.webp",
    downloadUrl: "/books/atos-dos-apostolos.pdf",
  },
];
