export type StudyItem = {
  slug: string;
  title: string;
  description: string;
  category: string;
  image: string;
};

export const studies: StudyItem[] = [
  {
    slug: "plano-da-salvacao",
    title: "O Plano da Salvação",
    description: "Uma visão clara e bíblica sobre redenção, graça e esperança em Cristo.",
    category: "Doutrina",
    image: "/images/content/bible.svg",
  },
  {
    slug: "as-tres-mensagens-angelicas",
    title: "As Três Mensagens Angélicas",
    description: "Entende o significado profético e missionário de Apocalipse 14.",
    category: "Profecia",
    image: "/images/content/faith.svg",
  },
  {
    slug: "o-sabado-na-biblia",
    title: "O Sábado na Bíblia",
    description: "Estudo sobre criação, mandamento, adoração e fidelidade.",
    category: "Mandamentos",
    image: "/images/content/study.svg",
  },
  {
    slug: "a-fe-de-jesus",
    title: "A Fé de Jesus",
    description: "Uma reflexão bíblica sobre confiança, obediência e perseverança em Cristo.",
    category: "Vida Cristã",
    image: "/images/content/faith.svg",
  },
  {
    slug: "a-segunda-vinda-de-cristo",
    title: "A Segunda Vinda de Cristo",
    description: "Promessas, sinais e esperança ligadas ao retorno visível de Jesus.",
    category: "Esperança",
    image: "/images/content/bible.svg",
  },
  {
    slug: "o-santuario-e-sua-mensagem",
    title: "O Santuário e Sua Mensagem",
    description: "Compreende a ligação entre o santuário, Cristo e o plano da redenção.",
    category: "Doutrina",
    image: "/images/content/study.svg",
  },
  {
    slug: "lei-e-graca",
    title: "Lei e Graça",
    description: "Como a lei de Deus e a graça de Cristo se harmonizam na experiência cristã.",
    category: "Doutrina",
    image: "/images/content/grace.svg",
  },
  {
    slug: "mordomia-crista",
    title: "Mordomia Cristã",
    description: "Princípios bíblicos sobre tempo, dons, recursos e fidelidade.",
    category: "Vida Cristã",
    image: "/images/content/faith.svg",
  },
  {
    slug: "a-oracao-que-transforma",
    title: "A Oração que Transforma",
    description: "Estudo sobre comunhão, dependência de Deus e poder espiritual na oração.",
    category: "Devocional",
    image: "/images/content/grace.svg",
  },
  {
    slug: "a-biblia-como-regra-de-fe",
    title: "A Bíblia como Regra de Fé",
    description: "Por que a Escritura deve ocupar o centro da crença e da prática cristã.",
    category: "Bíblia",
    image: "/images/content/bible.svg",
  },
  {
    slug: "o-espirito-santo-na-vida-do-crente",
    title: "O Espírito Santo na Vida do Crente",
    description: "A presença, a obra e a direção do Espírito Santo na vida cristã.",
    category: "Doutrina",
    image: "/images/content/faith.svg",
  },
  {
    slug: "a-justificacao-pela-fe",
    title: "A Justificação pela Fé",
    description: "A salvação em Cristo recebida pela fé, e não por méritos humanos.",
    category: "Graça",
    image: "/images/content/grace.svg",
  },
  {
    slug: "o-batismo-na-biblia",
    title: "O Batismo na Bíblia",
    description: "O significado do batismo como aliança, compromisso e novo começo.",
    category: "Doutrina",
    image: "/images/content/bible.svg",
  },
  {
    slug: "a-igreja-como-corpo-de-cristo",
    title: "A Igreja como Corpo de Cristo",
    description: "Unidade, missão e serviço no contexto da comunidade dos crentes.",
    category: "Igreja",
    image: "/images/content/study.svg",
  },
  {
    slug: "a-esperanca-da-ressurreicao",
    title: "A Esperança da Ressurreição",
    description: "A vitória sobre a morte à luz das promessas de Deus.",
    category: "Esperança",
    image: "/images/content/faith.svg",
  },
  {
    slug: "o-juizo-investigativo",
    title: "O Juízo Investigativo",
    description: "Uma abordagem bíblica e profética sobre juízo, intercessão e esperança.",
    category: "Profecia",
    image: "/images/content/bible.svg",
  },
  {
    slug: "o-poder-da-palavra",
    title: "O Poder da Palavra",
    description: "Como a Escritura transforma mente, coração e conduta.",
    category: "Bíblia",
    image: "/images/content/grace.svg",
  },
  {
    slug: "jejum-e-consagracao",
    title: "Jejum e Consagração",
    description: "Princípios espirituais ligados à humildade, oração e busca sincera.",
    category: "Devocional",
    image: "/images/content/study.svg",
  },
  {
    slug: "o-amor-como-marca-do-discipulo",
    title: "O Amor como Marca do Discípulo",
    description: "A evidência prática do evangelho na forma como tratamos os outros.",
    category: "Vida Cristã",
    image: "/images/content/grace.svg",
  },
  {
    slug: "a-vitoria-sobre-a-tentacao",
    title: "A Vitória sobre a Tentação",
    description: "Como resistir, vigiar e depender de Cristo nas lutas espirituais.",
    category: "Vida Cristã",
    image: "/images/content/faith.svg",
  },
  {
    slug: "cristo-nosso-sumo-sacerdote",
    title: "Cristo, Nosso Sumo Sacerdote",
    description: "O ministério de Cristo no santuário celestial e sua intercessão por nós.",
    category: "Doutrina",
    image: "/images/content/bible.svg",
  },
  {
    slug: "o-remanescente-fiel",
    title: "O Remanescente Fiel",
    description: "Características bíblicas do povo que permanece fiel nos últimos dias.",
    category: "Profecia",
    image: "/images/content/faith.svg",
  },
  {
    slug: "adoracao-verdadeira",
    title: "Adoração Verdadeira",
    description: "O que significa adorar a Deus em espírito, verdade e obediência.",
    category: "Adoração",
    image: "/images/content/study.svg",
  },
  {
    slug: "a-paz-que-vem-de-deus",
    title: "A Paz que Vem de Deus",
    description: "Uma reflexão bíblica sobre descanso interior e confiança no Senhor.",
    category: "Esperança",
    image: "/images/content/grace.svg",
  },
  {
    slug: "o-valor-da-santificacao",
    title: "O Valor da Santificação",
    description: "Crescimento espiritual diário pela graça e pelo poder de Deus.",
    category: "Vida Cristã",
    image: "/images/content/faith.svg",
  },
  {
    slug: "a-cruz-e-o-perdao",
    title: "A Cruz e o Perdão",
    description: "O centro do evangelho revelado no sacrifício de Cristo.",
    category: "Graça",
    image: "/images/content/grace.svg",
  },
  {
    slug: "a-fidelidade-nos-dizimos-e-ofertas",
    title: "A Fidelidade nos Dízimos e Ofertas",
    description: "Princípios bíblicos de fidelidade e gratidão no sustento da obra.",
    category: "Mordomia",
    image: "/images/content/study.svg",
  },
  {
    slug: "a-voz-de-deus-na-consciencia",
    title: "A Voz de Deus na Consciência",
    description: "Como discernir a vontade divina com sensibilidade espiritual.",
    category: "Devocional",
    image: "/images/content/bible.svg",
  },
  {
    slug: "o-evangelho-eterno",
    title: "O Evangelho Eterno",
    description: "A mensagem central da redenção desde o princípio até o fim.",
    category: "Evangelho",
    image: "/images/content/faith.svg",
  },
  {
    slug: "a-escolha-entre-babilonia-e-sihao",
    title: "A Escolha entre Babilónia e Sião",
    description: "Um contraste profético entre confusão religiosa e fidelidade a Deus.",
    category: "Profecia",
    image: "/images/content/study.svg",
  },
  {
    slug: "a-luz-do-mundo",
    title: "A Luz do Mundo",
    description: "Cristo como a verdadeira luz que ilumina o caminho espiritual.",
    category: "Cristo",
    image: "/images/content/faith.svg",
  },
  {
    slug: "o-caminho-estreito",
    title: "O Caminho Estreito",
    description: "A jornada cristã marcada por escolhas firmes e fidelidade.",
    category: "Vida Cristã",
    image: "/images/content/study.svg",
  },
  {
    slug: "o-perigo-da-indiferenca",
    title: "O Perigo da Indiferença",
    description: "Como a falta de zelo espiritual pode afastar da verdade.",
    category: "Advertência",
    image: "/images/content/bible.svg",
  },
  {
    slug: "a-graca-transformadora",
    title: "A Graça Transformadora",
    description: "A graça que não apenas perdoa, mas também transforma.",
    category: "Graça",
    image: "/images/content/grace.svg",
  },
  {
    slug: "a-importancia-da-vigilancia",
    title: "A Importância da Vigilância",
    description: "Estar atento espiritualmente em tempos de provação.",
    category: "Profecia",
    image: "/images/content/faith.svg",
  },
  {
    slug: "o-chamado-a-santidade",
    title: "O Chamado à Santidade",
    description: "Separação do pecado e dedicação total a Deus.",
    category: "Vida Cristã",
    image: "/images/content/study.svg",
  },
  {
    slug: "o-exemplo-de-cristo",
    title: "O Exemplo de Cristo",
    description: "Vida, caráter e missão como modelo para o crente.",
    category: "Cristo",
    image: "/images/content/bible.svg",
  },
  {
    slug: "a-verdade-que-liberta",
    title: "A Verdade que Liberta",
    description: "A verdade bíblica como caminho para liberdade espiritual.",
    category: "Bíblia",
    image: "/images/content/faith.svg",
  },
  {
    slug: "o-tempo-do-fim",
    title: "O Tempo do Fim",
    description: "Sinais, profecias e preparação para os últimos dias.",
    category: "Profecia",
    image: "/images/content/study.svg",
  },
  {
    slug: "a-confianca-em-deus",
    title: "A Confiança em Deus",
    description: "Aprender a descansar nas promessas divinas.",
    category: "Esperança",
    image: "/images/content/grace.svg",
  },
  {
    slug: "a-alianca-eterna",
    title: "A Aliança Eterna",
    description: "A fidelidade de Deus revelada na sua aliança com o seu povo.",
    category: "Doutrina",
    image: "/images/content/bible.svg",
  },
  {
    slug: "o-chamado-a-reforma",
    title: "O Chamado à Reforma",
    description: "Uma convocação bíblica à renovação espiritual, moral e prática.",
    category: "Reforma",
    image: "/images/content/study.svg",
  },
  {
    slug: "o-fruto-do-espirito",
    title: "O Fruto do Espírito",
    description: "As marcas visíveis de uma vida transformada pelo Espírito Santo.",
    category: "Vida Cristã",
    image: "/images/content/grace.svg",
  },
  {
    slug: "a-firmeza-na-palavra",
    title: "A Firmeza na Palavra",
    description: "Como permanecer ancorado na Escritura em tempos de confusão.",
    category: "Bíblia",
    image: "/images/content/faith.svg",
  },
  {
    slug: "o-ministerio-da-reconciliacao",
    title: "O Ministério da Reconciliação",
    description: "O chamado cristão para restaurar relações e apontar para Cristo.",
    category: "Missão",
    image: "/images/content/grace.svg",
  },
  {
    slug: "o-preco-do-discipulado",
    title: "O Preço do Discipulado",
    description: "Seguir Jesus envolve renúncia, fidelidade e perseverança.",
    category: "Discipulado",
    image: "/images/content/study.svg",
  },
  {
    slug: "a-sabedoria-que-vem-do-alto",
    title: "A Sabedoria que Vem do Alto",
    description: "Discernimento espiritual para decisões, caráter e serviço.",
    category: "Sabedoria",
    image: "/images/content/bible.svg",
  },
  {
    slug: "o-poder-do-testemunho",
    title: "O Poder do Testemunho",
    description: "Como a experiência pessoal com Deus fortalece a missão e a fé.",
    category: "Missão",
    image: "/images/content/faith.svg",
  },
  {
    slug: "a-escola-da-paciencia",
    title: "A Escola da Paciência",
    description: "Aprender a esperar em Deus com esperança, maturidade e confiança.",
    category: "Vida Cristã",
    image: "/images/content/grace.svg",
  },
  {
    slug: "esperanca-em-meio-a-crise",
    title: "Esperança em Meio à Crise",
    description: "Promessas bíblicas para dias difíceis, ansiedade e incerteza.",
    category: "Esperança",
    image: "/images/content/study.svg",
  },
  {
    slug: "o-reino-que-nao-passara",
    title: "O Reino que Não Passará",
    description: "A esperança do reino eterno de Deus acima de todos os reinos humanos.",
    category: "Profecia",
    image: "/images/content/bible.svg",
  },
];

export function getStudies() {
  return studies;
}

export function getStudyBySlug(slug: string) {
  return studies.find((study) => study.slug === slug) || null;
}
